export interface ProductSpecifications {
  dimensions?: string;
  wireDiameter?: string;
  meshAperture?: string;
  surfaceTreatment?: string;
  material?: string;
  weight?: string;
  tensileStrength?: string;
  coating?: string;
  width?: string;
  length?: string;
  height?: string;
  rollLength?: string;
  colors?: string;
  post?: string;
  frame?: string;
  infill?: string;
  panelSize?: string;
  panelHeight?: string;
  panelWidth?: string;
  wallHeight?: string;
  unitSize?: string;
  geotextile?: string;
  geogrid?: string;
  blastResistance?: string;
  ballistic?: string;
  impactResistance?: string;
  antiRam?: string;
  noiseReduction?: string;
  windLoad?: string;
  fireRating?: string;
  standard?: string;
  anchor?: string;
  rope?: string;
  brakingElement?: string;
  knotType?: string;
  barbSpacing?: string;
  barbLength?: string;
  loopsPerCoil?: string;
  coilDiameter?: string;
  bladeType?: string;
  bladeThickness?: string;
  wireGauge?: string;
  weaveType?: string;
  structure?: string;
  face?: string;
  facePlate?: string;
  soundAbsorbing?: string;
  connection?: string;
  foundation?: string;
  lifespan?: string;
  breakingStrength?: string;
  model?: string;
  net?: string;
  railType?: string;
  railSize?: string;
  outerMesh?: string;
  innerMesh?: string;
  coreWire?: string;
  selvage?: string;
  rollWeight?: string;
  base?: string;
}

export interface Product {
  id: string;
  sku: string;
  slug: string;
  categorySlug: string;
  names: Record<string, string>;
  shortDescriptions: Record<string, string>;
  fullDescriptions: Record<string, string>;
  specifications: ProductSpecifications;
  specifications_zh?: ProductSpecifications;
  specifications_vi?: ProductSpecifications;
  specifications_th?: ProductSpecifications;
  applications: string[];
  applications_zh?: string[];
  applications_vi?: string[];
  applications_th?: string[];
  images: string[];
  moq: number;
  priceUsd?: number;
  priceRemark?: string;
  isFeatured: boolean;
  seoTitle?: Record<string, string>;
  seoKeywords?: Record<string, string>;
  seoDescription?: Record<string, string>;
  faq?: Record<string, Array<{q: string; a: string}>>;
  createdAt: string;
  sortWeight?: number;
  category_name_en?: string;
  category_name_zh?: string;
  [key: string]: any;
}

export interface Category {
  id: string;
  slug: string;
  parentSlug?: string;
  names: Record<string, string>;
  descriptions: Record<string, string>;
  image?: string;
  productCount?: number;
  children?: Category[];
}
